name: PHP Unit Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  php_unit:
    name: php unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js (.node-version)
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Cache multiple paths
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Install Node Scripts
      run: npm install
    - name: Install Composer Packages
      run: composer install
    - name: Build
      run: npm run build
    - name: Run @wordpress/env
      run: |
        n=0
        until [ $n -ge 5 ]
        do
            npm run wp-env start --update && break
            n=$[$n+1]
            echo "Retrying wp-env start --update ($n)..."
            sleep 15
        done
    - name: Install & Activate Lightning Theme
      run:  npm run wp-env run tests-cli --env-cwd='wp-content/plugins/lightning-g3-evergreen' wp theme install lightning --activate
    - name: Install & Activate Lightning G3 Pro Unit
      run: npm run wp-env run tests-cli --env-cwd='wp-content/plugins/lightning-g3-evergreen' wp theme install ${{ secrets.G3_PRO_UNIT_URL }} --activate
    - name: PHP Unit Test
      run: npm run phpunit
